parameters:
#    social_tags.example.class: nlescure\SocialTagsBundle\Example

services:
#    social_tags.example:
#        class: %social_tags.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
